--1

ALTER TABLE DEPOSIT ADD CITY VARCHAR(50),PINCODE INT
SELECT * FROM DEPOSIT

--2
ALTER TABLE DEPOSIT ALTER COLUMN CNAME VARCHAR(35)

--3
ALTER TABLE DEPOSIT ALTER COLUMN AMOUNT INT
--4
SP_RENAME 'DEPOSIT.ACTNO','ANO'

--5
ALTER TABLE DEPOSIT DROP COLUMN CITY

--6
SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL'

--PART B
--1
SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'

--2
ALTER TABLE DEPOSIT_DETAIL DROP COLUMN AOPENDATE

--3
SP_RENAME 'DEPOSIT_DETAIL.CNAME','CUSTOMERNAME'




--PART C execute nathi thatu ky




--1
ALTER TABLE DEPOSIT_DETAIL ADD CITY VARCHAR(20)NOT NULL,BACKLOG INT

--2
ALTER TABLE DEPOSIT_DETAIL ALTER COLUMN CNAME VARCHAR(35)

--3
ALTER TABLE DEPOSIT_DETAIL ALTER COLUMN CPI INT
--4
SP_RENAME 'DEPOSIT_DETAIL.ENROLLMENT_NO','ENO'

--5
ALTER TABLE DEPOSIT_DETAIL DROP COLUMN CITY

--6
SP_RENAME 'DEPOSIT_DETAIL','STUDENT_MASTER'


--DELETE
--PART A

--1
DELETE FROM DEPOSIT_DETAIL WHERE AMOUNT >=4000

--2
DELETE FROM DEPOSIT_DETAIL WHERE BNAME = 'CHANDI'
--3
DELETE FROM DEPOSIT_DETAIL WHERE ANO>105

--4
TRUNCATE TABLE DEPOSIT_DETAIL

--5
DROP TABLE DEPOSIT_DATAIL

--PART B
CREATE TABLE EMPLOYEE_MASTER(

	EMPNO INT,
	EMPNAME VARCHAR(50),
	JOININGDATE DATETIME,
	SALARY DECIMAL(8,2),
	CITY VARCHAR(20)
);
INSERT INTO EMPLOYEE_MASTER (EMPNO,EMPNAME,JOININGDATE,SALARY,CITY) VALUES (101,'KEYUR','2002-01-05',12000.00,'RAJKOT');
INSERT INTO EMPLOYEE_MASTER (EMPNO,EMPNAME,JOININGDATE,SALARY,CITY) VALUES (102,'HARDIK','2004-02-15',14000.00,'AHEMDABAD');
INSERT INTO EMPLOYEE_MASTER (EMPNO,EMPNAME,JOININGDATE,SALARY,CITY) VALUES (103,'KAJAL','2006-03-14',15000.00,'BARODA');
INSERT INTO EMPLOYEE_MASTER (EMPNO,EMPNAME,JOININGDATE,SALARY,CITY) VALUES (104,'BHOOMI','2005-06-23',12000.00,'AHEMDABAD');
INSERT INTO EMPLOYEE_MASTER (EMPNO,EMPNAME,JOININGDATE,SALARY,CITY) VALUES (105,'HARMIT','2004-02-15',14000.00,'RAJKOT');
INSERT INTO EMPLOYEE_MASTER (EMPNO,EMPNAME,JOININGDATE,SALARY,CITY) VALUES (106,'MITESH','2001-09-25',5000.00,'JAMNAGAR');
INSERT INTO EMPLOYEE_MASTER (EMPNO,EMPNAME,JOININGDATE,SALARY,CITY) VALUES (107,'MEERA',NULL,7000.00,'MORBI');
INSERT INTO EMPLOYEE_MASTER (EMPNO,EMPNAME,JOININGDATE,SALARY,CITY) VALUES (108,'KISHAN','2003-02-06',10000.00,NULL);

SELECT * FROM EMPLOYEE_MASTER
--1
DELETE FROM EMPLOYEE_MASTERL WHERE SALARY>=14000
--2
DELETE FROM EMPLOYEE_MASTERL WHERE CITY='RAJKOT'
--3
DELETE FROM EMPLOYEE_MASTERL WHERE JOININGDATE<'2007-01-01'
--4
DELETE FROM EMPLOYEE_MASTERL WHERE JOININGDATE IS NULL AND NAME IS NOT NULL
--5
DELETE TOP 50 PERCENT  FROM EMPLOYEE_MASTERL WHERE SALARY>=14000
--6
DELETE FROM EMPLOYEE_MASTERL WHERE CITY IS NOT NULL
--7
TRUNCATE TABLE EMPLOYEE_MASTER
--8
DROP TABLE EMPLOYEE_MASTER

--PART C
--1
TRUNCATE TO USE FOR DELETE TABLE DATA 
DROP USE TO FOR DELETE FULL TABLE
